/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type ActionName =
  | "RocketOneAction.003"
  | "Cube.005Action"
  | "Cube.006Action"
  | "IcosphereAction.003"
  | "Icosphere.002Action.005"
  | "Icosphere.003Action.005"
  | "Icosphere.004Action.003"
  | "Icosphere.005Action.005"
  | "Icosphere.001Action.006"
  | "RocketModel.003Action"
  | "Person.012Action.001"
  | "Sphere.012Action.001"
  | "Person.024Action"
  | "Sphere.025Action"
  | "Person.025Action"
  | "Sphere.026Action"
  | "Person.026Action"
  | "Sphere.027Action"
  | "Person.027Action"
  | "Sphere.028Action"
  | "TruckOneAction"
  | "CircleAction.001"
  | "BirdNestImages.001Action"
  | "ImagePWLanding.005Action"
  | "ImagePWLanding.007Action"
  | "TruckTwo.003Action"
  | "Cube.002Action"
  | "Cube.079Action"
  | "Cube.080Action"
  | "Cube.081Action"
  | "Cube.082Action"
  | "Cube.083Action"
  | "Cube.084Action"
  | "Cube.085Action"
  | "Cube.086Action";
interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Cube061_1: THREE.Mesh;
    Cube061_2: THREE.Mesh;
    Cube059_1: THREE.Mesh;
    Cube059_2: THREE.Mesh;
    Cube060_1: THREE.Mesh;
    Cube060_2: THREE.Mesh;
    Icosphere001: THREE.Mesh;
    Icosphere002: THREE.Mesh;
    Icosphere003: THREE.Mesh;
    Icosphere004: THREE.Mesh;
    Icosphere005: THREE.Mesh;
    RocketFlame001: THREE.Mesh;
    Cube058_1: THREE.Mesh;
    Cube058_2: THREE.Mesh;
    Cube101_1: THREE.Mesh;
    Cube101_2: THREE.Mesh;
    Ground: THREE.Mesh;
    ImagePWLanding: THREE.Mesh;
    ImagePWLanding001: THREE.Mesh;
    ImagePWLanding002: THREE.Mesh;
    ImagePWLanding003: THREE.Mesh;
    Plane001: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Person006: THREE.Mesh;
    Person013: THREE.Mesh;
    Sphere013_1: THREE.Mesh;
    Sphere014: THREE.Mesh;
    Cube062_1: THREE.Mesh;
    Cube062_2: THREE.Mesh;
    Cube063_1: THREE.Mesh;
    Cube063_2: THREE.Mesh;
    RocketStorage: THREE.Mesh;
    Cube007_1: THREE.Mesh;
    Cube007_2: THREE.Mesh;
    Cube008_1: THREE.Mesh;
    Cube008_2: THREE.Mesh;
    Cube009: THREE.Mesh;
    Cube009_1: THREE.Mesh;
    Cube102_1: THREE.Mesh;
    Cube102_2: THREE.Mesh;
    Cube012_1: THREE.Mesh;
    Cube012_2: THREE.Mesh;
    Cube014_1: THREE.Mesh;
    Cube014_2: THREE.Mesh;
    Cube015_1: THREE.Mesh;
    Cube015_2: THREE.Mesh;
    Cube103_1: THREE.Mesh;
    Cube103_2: THREE.Mesh;
    Cube018_1: THREE.Mesh;
    Cube018_2: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube022_1: THREE.Mesh;
    Cube022_2: THREE.Mesh;
    Cube045_1: THREE.Mesh;
    Cube045_2: THREE.Mesh;
    Cube046_1: THREE.Mesh;
    Cube046_2: THREE.Mesh;
    Cube104_1: THREE.Mesh;
    Cube104_2: THREE.Mesh;
    Cube105_1: THREE.Mesh;
    Cube105_2: THREE.Mesh;
    Cube106_1: THREE.Mesh;
    Cube106_2: THREE.Mesh;
    Cube107_1: THREE.Mesh;
    Cube107_2: THREE.Mesh;
    Cube108_1: THREE.Mesh;
    Cube108_2: THREE.Mesh;
    Cube109_1: THREE.Mesh;
    Cube109_2: THREE.Mesh;
    Cube049_1: THREE.Mesh;
    Cube049_2: THREE.Mesh;
    Cube049_3: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube050_1: THREE.Mesh;
    Cube050_2: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube030: THREE.Mesh;
    ImagePWLanding004: THREE.Mesh;
    ImagePWLanding006: THREE.Mesh;
    ImagePWLanding008: THREE.Mesh;
    ImagePWLanding009: THREE.Mesh;
    PWEditSliderImage: THREE.Mesh;
    Cube036: THREE.Mesh;
    Person: THREE.Mesh;
    Sphere: THREE.Mesh;
    Person002: THREE.Mesh;
    Sphere001: THREE.Mesh;
    StaticBuildingPeople: THREE.Mesh;
    Person001: THREE.Mesh;
    Person003: THREE.Mesh;
    Person004: THREE.Mesh;
    Person005: THREE.Mesh;
    Person007: THREE.Mesh;
    Person008: THREE.Mesh;
    Person009: THREE.Mesh;
    Person010: THREE.Mesh;
    Person011: THREE.Mesh;
    Sphere002_1: THREE.Mesh;
    Sphere003: THREE.Mesh;
    Sphere004: THREE.Mesh;
    Sphere005: THREE.Mesh;
    Sphere006: THREE.Mesh;
    Sphere007: THREE.Mesh;
    Sphere008: THREE.Mesh;
    Sphere009: THREE.Mesh;
    Sphere010: THREE.Mesh;
    Sphere011: THREE.Mesh;
    Person012: THREE.Mesh;
    Sphere012: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube110_1: THREE.Mesh;
    Cube110_2: THREE.Mesh;
    Cube111_1: THREE.Mesh;
    Cube111_2: THREE.Mesh;
    Cube112_1: THREE.Mesh;
    Cube112_2: THREE.Mesh;
    Cube113_1: THREE.Mesh;
    Cube113_2: THREE.Mesh;
    Cube114_1: THREE.Mesh;
    Cube114_2: THREE.Mesh;
    Cube115_1: THREE.Mesh;
    Cube115_2: THREE.Mesh;
    Cube116: THREE.Mesh;
    Cube116_1: THREE.Mesh;
    Cube117: THREE.Mesh;
    Cube117_1: THREE.Mesh;
    Cube001: THREE.Mesh;
    Cube097: THREE.Mesh;
    Cube098: THREE.Mesh;
    Cube099: THREE.Mesh;
    Garage: THREE.Mesh;
    ConstructionTrucks: THREE.Mesh;
    Cube025: THREE.Mesh;
    Cube026: THREE.Mesh;
    Cube027: THREE.Mesh;
    Cube028: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube050_3: THREE.Mesh;
    Cube051: THREE.Mesh;
    Cube002_1: THREE.Mesh;
    Cube002_2: THREE.Mesh;
    Fuel_Tanks: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Person024: THREE.Mesh;
    Sphere025: THREE.Mesh;
    Person025: THREE.Mesh;
    Sphere026: THREE.Mesh;
    Cube192: THREE.Mesh;
    Cube192_1: THREE.Mesh;
    Cube192_2: THREE.Mesh;
    Circle: THREE.Mesh;
    Person026: THREE.Mesh;
    Sphere027: THREE.Mesh;
    Person027: THREE.Mesh;
    Sphere028: THREE.Mesh;
    Cube070: THREE.Mesh;
    Cube197: THREE.Mesh;
    Cube197_1: THREE.Mesh;
    Person028: THREE.Mesh;
    Sphere029: THREE.Mesh;
    Person029: THREE.Mesh;
    Sphere030: THREE.Mesh;
    Cube203: THREE.Mesh;
    Cube203_1: THREE.Mesh;
    Cube204: THREE.Mesh;
    Cube204_1: THREE.Mesh;
    Cube205: THREE.Mesh;
    Cube205_1: THREE.Mesh;
    Cube206: THREE.Mesh;
    Cube206_1: THREE.Mesh;
    Person030: THREE.Mesh;
    Sphere031: THREE.Mesh;
    Person031: THREE.Mesh;
    Sphere032: THREE.Mesh;
    Person032: THREE.Mesh;
    Sphere033: THREE.Mesh;
    Person033: THREE.Mesh;
    Sphere034: THREE.Mesh;
    Person034: THREE.Mesh;
    Sphere035: THREE.Mesh;
    Cube003: THREE.Mesh;
    Person035: THREE.Mesh;
    Sphere036: THREE.Mesh;
    Person036: THREE.Mesh;
    Sphere037: THREE.Mesh;
    Person014: THREE.Mesh;
    Sphere015: THREE.Mesh;
    Person015: THREE.Mesh;
    Sphere016: THREE.Mesh;
    Person020: THREE.Mesh;
    Sphere021: THREE.Mesh;
    Person021: THREE.Mesh;
    Sphere022: THREE.Mesh;
    Person016: THREE.Mesh;
    Sphere017: THREE.Mesh;
    Person017: THREE.Mesh;
    Sphere018: THREE.Mesh;
    Person018: THREE.Mesh;
    Sphere019: THREE.Mesh;
    Person019: THREE.Mesh;
    Sphere020: THREE.Mesh;
    Person037: THREE.Mesh;
    Sphere038: THREE.Mesh;
    Person038: THREE.Mesh;
    Sphere039: THREE.Mesh;
    Cube064_1: THREE.Mesh;
    Cube064_2: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube013_1: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube015: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube018: THREE.Mesh;
    BirdNestImages: THREE.Mesh;
    BirdNestImages001: THREE.Mesh;
    ImagePWLanding005: THREE.Mesh;
    ImagePWLanding007: THREE.Mesh;
    Cube084_1: THREE.Mesh;
    Cube084_2: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube062: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube064: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube066: THREE.Mesh;
    Cube067: THREE.Mesh;
    Cube068: THREE.Mesh;
    Cube069: THREE.Mesh;
    Cube147: THREE.Mesh;
    Cube147_1: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube079: THREE.Mesh;
    Cube080: THREE.Mesh;
    Cube081: THREE.Mesh;
    Cube082: THREE.Mesh;
    Cube083: THREE.Mesh;
    Cube084: THREE.Mesh;
    Cube085: THREE.Mesh;
    Cube086: THREE.Mesh;
    Cube157: THREE.Mesh;
    Cube157_1: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Cube057: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube167: THREE.Mesh;
    Cube167_1: THREE.Mesh;
    Cube087: THREE.Mesh;
    Cube088: THREE.Mesh;
    Cube089: THREE.Mesh;
    Cube090: THREE.Mesh;
    Cube091: THREE.Mesh;
    Cube092: THREE.Mesh;
    Cube093: THREE.Mesh;
    Cube094: THREE.Mesh;
    Cube095: THREE.Mesh;
    Cube207: THREE.Mesh;
    Cube207_1: THREE.Mesh;
    Cube078: THREE.Mesh;
    Cube096: THREE.Mesh;
    Cube100: THREE.Mesh;
    Cube101: THREE.Mesh;
    Cube102: THREE.Mesh;
    Cube103: THREE.Mesh;
    Cube104: THREE.Mesh;
    Cube105: THREE.Mesh;
    Cube106: THREE.Mesh;
    Cube217: THREE.Mesh;
    Cube217_1: THREE.Mesh;
    Cube107: THREE.Mesh;
    Cube108: THREE.Mesh;
    Cube109: THREE.Mesh;
    Cube110: THREE.Mesh;
    Cube111: THREE.Mesh;
    Cube112: THREE.Mesh;
    Cube113: THREE.Mesh;
    Cube114: THREE.Mesh;
    Cube115: THREE.Mesh;
    Text: THREE.Mesh;
    Text001: THREE.Mesh;
    Text002: THREE.Mesh;
    Text003: THREE.Mesh;
    Text004: THREE.Mesh;
    Text005: THREE.Mesh;
    Text006: THREE.Mesh;
    Text007: THREE.Mesh;
    Cylinder: THREE.Mesh;
  };
  materials: {
    ["Material.065"]: THREE.MeshStandardMaterial;
    Red: THREE.MeshStandardMaterial;
    ["Material.048"]: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.049"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    ["Material.013"]: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
    ["PWLanding.001"]: THREE.MeshStandardMaterial;
    PWGallery: THREE.MeshStandardMaterial;
    BlisselyLanding: THREE.MeshStandardMaterial;
    BlisselyHome: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.044"]: THREE.MeshStandardMaterial;
    ["Material.045"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
    ["Material.033"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    ["Material.034"]: THREE.MeshStandardMaterial;
    ["Material.032"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.035"]: THREE.MeshStandardMaterial;
    ["Material.036"]: THREE.MeshStandardMaterial;
    ["Material.037"]: THREE.MeshStandardMaterial;
    ["Material.042"]: THREE.MeshStandardMaterial;
    ["Material.043"]: THREE.MeshStandardMaterial;
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["Material.039"]: THREE.MeshStandardMaterial;
    ["Material.040"]: THREE.MeshStandardMaterial;
    ["Material.041"]: THREE.MeshStandardMaterial;
    ["Material.046"]: THREE.MeshStandardMaterial;
    ["Material.047"]: THREE.MeshStandardMaterial;
    ["Material.051"]: THREE.MeshStandardMaterial;
    ["Material.050"]: THREE.MeshStandardMaterial;
    ["Material.052"]: THREE.MeshStandardMaterial;
    ["Material.057"]: THREE.MeshStandardMaterial;
    ["Material.056"]: THREE.MeshStandardMaterial;
    ["Material.055"]: THREE.MeshStandardMaterial;
    ["Material.054"]: THREE.MeshStandardMaterial;
    ["Material.053"]: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.027"]: THREE.MeshStandardMaterial;
    ["Material.020"]: THREE.MeshStandardMaterial;
    ["Material.025"]: THREE.MeshStandardMaterial;
    ["Material.026"]: THREE.MeshStandardMaterial;
    ["Material.024"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    ["Material.063"]: THREE.MeshStandardMaterial;
    ["Material.070"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.031"]: THREE.MeshStandardMaterial;
    BirdNestProfile: THREE.MeshStandardMaterial;
    BirdNestHome: THREE.MeshStandardMaterial;
    BirdNestMessageFeed: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["default"]: THREE.MeshStandardMaterial;
    ["Material.028"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function LandingAnimation(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    "/LandingAnimationCompressed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Cube.005Action"]?.play();
    actions["Cube.006Action"]?.play();
    actions["Icosphere.001Action.006"]?.play();
    actions["Icosphere.002Action.005"]?.play();
    actions["Icosphere.003Action.005"]?.play();
    actions["Icosphere.004Action.003"]?.play();
    actions["Icosphere.005Action.005"]?.play();
    actions["IcosphereAction.003"]?.play();
    actions["RocketOneAction.003"]?.play();
    actions["Person.012Action.001"]?.play();
    actions["Sphere.012Action.001"]?.play();
    actions["Person.024Action"]?.play();
    actions["Sphere.025Action"]?.play();
    actions["Person.025Action"]?.play();
    actions["Sphere.026Action"]?.play();
    actions["Person.026Action"]?.play();
    actions["Sphere.027Action"]?.play();
    actions["Person.027Action"]?.play();
    actions["Sphere.028Action"]?.play();
    actions.TruckOneAction?.play();
    actions["CircleAction.001"]?.play();
    actions["BirdNestImages.001Action"]?.play();
    actions["ImagePWLanding.005Action"]?.play();
    actions["ImagePWLanding.007Action"]?.play();
    actions["TruckTwo.003Action"]?.play();
    actions["Cube.002Action"]?.play();
    actions["Cube.079Action"]?.play();
    actions["Cube.080Action"]?.play();
    actions["Cube.081Action"]?.play();
    actions["Cube.082Action"]?.play();
    actions["Cube.083Action"]?.play();
    actions["Cube.084Action"]?.play();
    actions["Cube.085Action"]?.play();
    actions["Cube.086Action"]?.play();
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="RocketOne"
          position={[-6.31, 13.51, -3.63]}
          rotation={[0, -0.73, 0]}
          scale={0.11}
        >
          <mesh
            name="Cube061_1"
            geometry={nodes.Cube061_1.geometry}
            material={materials["Material.065"]}
          />
          <mesh
            name="Cube061_2"
            geometry={nodes.Cube061_2.geometry}
            material={materials.Red}
          />
          <group name="Cube005" position={[2.3, -0.4, 0]} scale={[1, 0.58, 1]}>
            <mesh
              name="Cube059_1"
              geometry={nodes.Cube059_1.geometry}
              material={materials["Material.048"]}
            />
            <mesh
              name="Cube059_2"
              geometry={nodes.Cube059_2.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group
            name="Cube006"
            position={[-2.32, -0.4, 0]}
            scale={[1, 0.58, 1]}
          >
            <mesh
              name="Cube060_1"
              geometry={nodes.Cube060_1.geometry}
              material={materials["Material.049"]}
            />
            <mesh
              name="Cube060_2"
              geometry={nodes.Cube060_2.geometry}
              material={materials["Material.006"]}
            />
          </group>
          <mesh
            name="Icosphere001"
            geometry={nodes.Icosphere001.geometry}
            material={materials["Material.013"]}
            position={[-2.26, -4.35, 0.53]}
            rotation={[0, 0.09, 0]}
            scale={2.62}
          />
          <mesh
            name="Icosphere002"
            geometry={nodes.Icosphere002.geometry}
            material={materials["Material.013"]}
            position={[2.07, -4.46, 0.13]}
            rotation={[-0.33, -0.07, 0.42]}
            scale={2.62}
          />
          <mesh
            name="Icosphere003"
            geometry={nodes.Icosphere003.geometry}
            material={materials["Material.013"]}
            position={[-1.64, -7.13, 0.21]}
            rotation={[-0.71, -0.84, -0.34]}
            scale={2.62}
          />
          <mesh
            name="Icosphere004"
            geometry={nodes.Icosphere004.geometry}
            material={materials["Material.013"]}
            position={[1.06, -7.13, -0.04]}
            rotation={[-2.4, 0.37, -1.84]}
            scale={2.62}
          />
          <mesh
            name="Icosphere005"
            geometry={nodes.Icosphere005.geometry}
            material={materials["Material.013"]}
            position={[-0.02, -10.14, 0.06]}
            rotation={[2.63, 1.18, -1.81]}
            scale={2.62}
          />
          <mesh
            name="RocketFlame001"
            geometry={nodes.RocketFlame001.geometry}
            material={materials["Material.013"]}
            position={[-0.31, -4.46, 0.35]}
            rotation={[-1.36, -0.96, -0.55]}
            scale={2.62}
          />
          <group name="RocketModel003">
            <mesh
              name="Cube058_1"
              geometry={nodes.Cube058_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube058_2"
              geometry={nodes.Cube058_2.geometry}
              material={materials.Red}
            />
          </group>
        </group>
        <group
          name="RocketModel002"
          position={[2.03, 1.48, 0.43]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.11}
        >
          <mesh
            name="Cube101_1"
            geometry={nodes.Cube101_1.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            name="Cube101_2"
            geometry={nodes.Cube101_2.geometry}
            material={materials.Red}
          />
        </group>
        <mesh
          name="Ground"
          geometry={nodes.Ground.geometry}
          material={materials.Material}
          scale={[4, 1, 4]}
        />
        <mesh
          name="ImagePWLanding"
          geometry={nodes.ImagePWLanding.geometry}
          material={materials["PWLanding.001"]}
          position={[2.41, 3.29, -2.42]}
          rotation={[-Math.PI / 6, -1.57, 0]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="ImagePWLanding001"
          geometry={nodes.ImagePWLanding001.geometry}
          material={materials.PWGallery}
          position={[2.4, 2.45, -2.2]}
          rotation={[Math.PI / 6, 1.57, 0]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="ImagePWLanding002"
          geometry={nodes.ImagePWLanding002.geometry}
          material={materials.BlisselyLanding}
          position={[-1.06, 1.57, 3.73]}
          rotation={[2.55, 1.53, -2.67]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="ImagePWLanding003"
          geometry={nodes.ImagePWLanding003.geometry}
          material={materials.BlisselyHome}
          position={[1.53, 1.4, 3.37]}
          rotation={[-3.05, 1.07, 2.82]}
          scale={[0.09, 1.06, 2.03]}
        />
        <group
          name="SupplyDepotOne"
          position={[3.13, 1.11, 3.29]}
          rotation={[0, 0, 0.01]}
          scale={0.25}
        >
          <mesh
            name="Plane001"
            geometry={nodes.Plane001.geometry}
            material={materials["Material.003"]}
          />
          <mesh
            name="Plane001_1"
            geometry={nodes.Plane001_1.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            name="Person006"
            geometry={nodes.Person006.geometry}
            material={materials["Material.044"]}
            position={[-0.47, 0.03, 0.86]}
            rotation={[-0.01, -0.82, -1.58]}
            scale={[0.05, 0.02, 0.02]}
          />
          <mesh
            name="Person013"
            geometry={nodes.Person013.geometry}
            material={materials["Material.044"]}
            position={[-0.33, 0.03, 0.86]}
            rotation={[-0.01, -0.82, -1.58]}
            scale={[0.05, 0.02, 0.02]}
          />
          <mesh
            name="Sphere014"
            geometry={nodes.Sphere014.geometry}
            material={materials["Material.045"]}
            position={[-0.33, 0.11, 0.86]}
            rotation={[0, 0, -0.01]}
            scale={0.03}
          />
        </group>
        <group
          name="RocketOnePlatform"
          position={[-1.09, 1.2, 3.1]}
          scale={0.7}
        >
          <mesh
            name="Cube062_1"
            geometry={nodes.Cube062_1.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            name="Cube062_2"
            geometry={nodes.Cube062_2.geometry}
            material={materials["Material.033"]}
          />
          <group
            name="Cube007"
            position={[1.7, 0.12, -0.08]}
            rotation={[0, 0, -0.08]}
            scale={[1.25, 0.82, 0.16]}
          >
            <mesh
              name="Cube063_1"
              geometry={nodes.Cube063_1.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Cube063_2"
              geometry={nodes.Cube063_2.geometry}
              material={materials["Material.034"]}
            />
          </group>
        </group>
        <mesh
          name="RocketStorage"
          geometry={nodes.RocketStorage.geometry}
          material={materials["Material.032"]}
          position={[3.11, 1.18, 0.85]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.52, -0.19, -1.17]}
        >
          <group
            name="RocketModel004"
            position={[-0.01, -1.5, 0.75]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube007_1"
              geometry={nodes.Cube007_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube007_2"
              geometry={nodes.Cube007_2.geometry}
              material={materials.Red}
            />
            <group
              name="Cube019_1"
              position={[2.3, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube008_1"
                geometry={nodes.Cube008_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                name="Cube008_2"
                geometry={nodes.Cube008_2.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Cube020"
              position={[-2.32, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube009"
                geometry={nodes.Cube009.geometry}
                material={materials["Material.005"]}
              />
              {/* <mesh
                name="Cube009_1"
                geometry={nodes.Cube009_1.geometry}
                material={materials["Material.006"]}
              /> */}
            </group>
          </group>
          <group
            name="RocketModel005"
            position={[-0.01, -1.5, 0.38]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube102_1"
              geometry={nodes.Cube102_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube102_2"
              geometry={nodes.Cube102_2.geometry}
              material={materials.Red}
            />
          </group>
          <group
            name="RocketModel007"
            position={[-0.01, -1.5, 0.38]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube012_1"
              geometry={nodes.Cube012_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube012_2"
              geometry={nodes.Cube012_2.geometry}
              material={materials.Red}
            />
            <group
              name="Cube021_1"
              position={[2.3, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube014_1"
                geometry={nodes.Cube014_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                name="Cube014_2"
                geometry={nodes.Cube014_2.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Cube022"
              position={[-2.32, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube015_1"
                geometry={nodes.Cube015_1.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                name="Cube015_2"
                geometry={nodes.Cube015_2.geometry}
                material={materials["Material.006"]}
              />
            </group>
          </group>
          <group
            name="RocketModel008"
            position={[-0.01, -1.5, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube103_1"
              geometry={nodes.Cube103_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube103_2"
              geometry={nodes.Cube103_2.geometry}
              material={materials.Red}
            />
          </group>
          <group
            name="RocketModel009"
            position={[-0.01, -1.5, 0]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube018_1"
              geometry={nodes.Cube018_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube018_2"
              geometry={nodes.Cube018_2.geometry}
              material={materials.Red}
            />
            <group
              name="Cube023_1"
              position={[2.3, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube020_1"
                geometry={nodes.Cube020_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                name="Cube020_2"
                geometry={nodes.Cube020_2.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Cube024_1"
              position={[-2.32, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube022_1"
                geometry={nodes.Cube022_1.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                name="Cube022_2"
                geometry={nodes.Cube022_2.geometry}
                material={materials["Material.006"]}
              />
            </group>
            <group
              name="Cube033"
              position={[2.3, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube045_1"
                geometry={nodes.Cube045_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                name="Cube045_2"
                geometry={nodes.Cube045_2.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Cube034"
              position={[-2.32, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube046_1"
                geometry={nodes.Cube046_1.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                name="Cube046_2"
                geometry={nodes.Cube046_2.geometry}
                material={materials["Material.006"]}
              />
            </group>
          </group>
          <group
            name="RocketModel010"
            position={[-0.01, -1.5, -0.37]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube104_1"
              geometry={nodes.Cube104_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube104_2"
              geometry={nodes.Cube104_2.geometry}
              material={materials.Red}
            />
            <group
              name="Cube038"
              position={[2.3, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube105_1"
                geometry={nodes.Cube105_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                name="Cube105_2"
                geometry={nodes.Cube105_2.geometry}
                material={materials["Material.002"]}
              />
            </group>
            <group
              name="Cube039"
              position={[-2.32, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube106_1"
                geometry={nodes.Cube106_1.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                name="Cube106_2"
                geometry={nodes.Cube106_2.geometry}
                material={materials["Material.006"]}
              />
            </group>
          </group>
          <group
            name="RocketModel011"
            position={[-0.01, -1.5, -0.75]}
            rotation={[-Math.PI, 0, -Math.PI]}
            scale={[-0.21, -0.57, -0.09]}
          >
            <mesh
              name="Cube107_1"
              geometry={nodes.Cube107_1.geometry}
              material={materials["Material.007"]}
            />
            <mesh
              name="Cube107_2"
              geometry={nodes.Cube107_2.geometry}
              material={materials.Red}
            />
            <group
              name="Cube040"
              position={[-2.32, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube108_1"
                geometry={nodes.Cube108_1.geometry}
                material={materials["Material.005"]}
              />
              <mesh
                name="Cube108_2"
                geometry={nodes.Cube108_2.geometry}
                material={materials["Material.006"]}
              />
            </group>
            <group
              name="Cube041"
              position={[2.3, -0.4, 0]}
              scale={[1, 0.58, 1]}
            >
              <mesh
                name="Cube109_1"
                geometry={nodes.Cube109_1.geometry}
                material={materials["Material.008"]}
              />
              <mesh
                name="Cube109_2"
                geometry={nodes.Cube109_2.geometry}
                material={materials["Material.002"]}
              />
            </group>
          </group>
        </mesh>
        <group
          name="Cube"
          position={[1.21, 1.25, -2.34]}
          scale={[2.34, 0.28, 0.63]}
        >
          <mesh
            name="Cube049_1"
            geometry={nodes.Cube049_1.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            name="Cube049_2"
            geometry={nodes.Cube049_2.geometry}
            material={materials["Material.036"]}
          />
          <mesh
            name="Cube049_3"
            geometry={nodes.Cube049_3.geometry}
            material={materials["Material.037"]}
          />
        </group>
        <group
          name="Cube029"
          position={[2.38, 1.7, -2.34]}
          scale={[0.96, 0.2, 0.45]}
        >
          <mesh
            name="Cube050"
            geometry={nodes.Cube050.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube050_1"
            geometry={nodes.Cube050_1.geometry}
            material={materials["Material.036"]}
          />
          <mesh
            name="Cube050_2"
            geometry={nodes.Cube050_2.geometry}
            material={materials["Material.037"]}
          />
        </group>
        <mesh
          name="Cube035"
          geometry={nodes.Cube035.geometry}
          material={materials["Material.042"]}
          position={[1.87, 2.77, -2.31]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.07, -0.94, -0.07]}
        />
        <mesh
          name="Cube030"
          geometry={nodes.Cube030.geometry}
          material={materials["Material.043"]}
          position={[2.95, 2.77, -2.31]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.07, -0.94, -0.07]}
        />
        <mesh
          name="ImagePWLanding004"
          geometry={nodes.ImagePWLanding004.geometry}
          material={materials["PWLanding.001"]}
          position={[2.41, 3.29, -2.2]}
          rotation={[Math.PI / 6, 1.57, 0]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="ImagePWLanding006"
          geometry={nodes.ImagePWLanding006.geometry}
          material={materials.PWGallery}
          position={[2.4, 2.45, -2.42]}
          rotation={[-Math.PI / 6, -1.57, 0]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="ImagePWLanding008"
          geometry={nodes.ImagePWLanding008.geometry}
          material={materials["Material.038"]}
          position={[2.38, 1.52, -3.06]}
          rotation={[-0.12, -1.57, 0]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="ImagePWLanding009"
          geometry={nodes.ImagePWLanding009.geometry}
          material={materials["Material.039"]}
          position={[-2.43, 1.74, -3.72]}
          rotation={[-Math.PI / 6, -1.57, 0]}
          scale={[0.09, 1.06, 2.03]}
        />
        <mesh
          name="PWEditSliderImage"
          geometry={nodes.PWEditSliderImage.geometry}
          material={materials["Material.040"]}
          position={[-1.9, 1.62, -3.63]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.07, -0.53, -0.07]}
        >
          <mesh
            name="Cube036"
            geometry={nodes.Cube036.geometry}
            material={materials["Material.041"]}
            position={[-14.31, 0, 0]}
          />
        </mesh>
        <mesh
          name="Person"
          geometry={nodes.Person.geometry}
          material={materials["Material.044"]}
          position={[-1.57, 1.28, 0.03]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials["Material.045"]}
          position={[-1.57, 1.32, 0.03]}
          scale={0.02}
        />
        <mesh
          name="Person002"
          geometry={nodes.Person002.geometry}
          material={materials["Material.044"]}
          position={[-1.61, 1.28, -0.03]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere001"
          geometry={nodes.Sphere001.geometry}
          material={materials["Material.045"]}
          position={[-1.61, 1.32, -0.03]}
          scale={0.02}
        />
        <mesh
          name="StaticBuildingPeople"
          geometry={nodes.StaticBuildingPeople.geometry}
          material={materials["Material.044"]}
          position={[-0.99, 1.56, -2.27]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        >
          <mesh
            name="Person001"
            geometry={nodes.Person001.geometry}
            material={materials["Material.044"]}
            position={[0, 96.06, -123.83]}
          />
          <mesh
            name="Person003"
            geometry={nodes.Person003.geometry}
            material={materials["Material.044"]}
            position={[0, 105.95, -124.65]}
          />
          <mesh
            name="Person004"
            geometry={nodes.Person004.geometry}
            material={materials["Material.044"]}
            position={[0, 98.84, -117.92]}
          />
          <mesh
            name="Person005"
            geometry={nodes.Person005.geometry}
            material={materials["Material.044"]}
            position={[0, 1.43, -8.27]}
          />
          <mesh
            name="Person007"
            geometry={nodes.Person007.geometry}
            material={materials["Material.044"]}
            position={[0, -0.21, -97.35]}
          />
          <mesh
            name="Person008"
            geometry={nodes.Person008.geometry}
            material={materials["Material.044"]}
            position={[0, 13.19, -102.78]}
          />
          <mesh
            name="Person009"
            geometry={nodes.Person009.geometry}
            material={materials["Material.044"]}
            position={[0, 16.58, -94.16]}
          />
          <mesh
            name="Person010"
            geometry={nodes.Person010.geometry}
            material={materials["Material.044"]}
            position={[0, 13.23, -84.22]}
          />
          <mesh
            name="Person011"
            geometry={nodes.Person011.geometry}
            material={materials["Material.044"]}
            position={[0, 1.18, -83.65]}
          />
          <mesh
            name="Sphere003"
            geometry={nodes.Sphere003.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 106.02, -124.69]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere004"
            geometry={nodes.Sphere004.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 98.91, -117.96]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere005"
            geometry={nodes.Sphere005.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 1.5, -8.32]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere006"
            geometry={nodes.Sphere006.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 0.07, -0.05]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere007"
            geometry={nodes.Sphere007.geometry}
            material={materials["Material.045"]}
            position={[-1.47, -0.14, -97.39]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere008"
            geometry={nodes.Sphere008.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 13.26, -102.83]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere009"
            geometry={nodes.Sphere009.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 16.65, -94.21]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere010"
            geometry={nodes.Sphere010.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 13.3, -84.27]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
          <mesh
            name="Sphere011"
            geometry={nodes.Sphere011.geometry}
            material={materials["Material.045"]}
            position={[-1.47, 1.25, -83.69]}
            rotation={[-0.82, 0.02, 1.56]}
            scale={[1.97, 0.6, 1.96]}
          />
        </mesh>
        <mesh
          name="Person012"
          geometry={nodes.Person012.geometry}
          material={materials["Material.044"]}
          position={[1.24, 1.56, -2.88]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere012"
          geometry={nodes.Sphere012.geometry}
          material={materials["Material.045"]}
          position={[1.24, 1.6, -2.88]}
          scale={0.02}
        />
        <mesh
          name="Cube037"
          geometry={nodes.Cube037.geometry}
          material={materials["Material.046"]}
          position={[1.89, 1.19, 1.24]}
          scale={[0.36, 0.15, 1]}
        />
        <group
          name="Cube042"
          position={[-2.94, 1.19, 3.14]}
          scale={[0.66, 0.08, 0.08]}
        >
          <mesh
            name="Cube110_1"
            geometry={nodes.Cube110_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube110_2"
            geometry={nodes.Cube110_2.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube043"
          position={[-2.94, 1.19, 2.87]}
          scale={[0.66, 0.08, 0.08]}
        >
          <mesh
            name="Cube111_1"
            geometry={nodes.Cube111_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube111_2"
            geometry={nodes.Cube111_2.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube044"
          position={[-2.94, 1.19, 2.61]}
          scale={[0.66, 0.08, 0.08]}
        >
          <mesh
            name="Cube112_1"
            geometry={nodes.Cube112_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube112_2"
            geometry={nodes.Cube112_2.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube045"
          position={[-2.94, 1.19, 2.34]}
          scale={[0.66, 0.08, 0.08]}
        >
          <mesh
            name="Cube113_1"
            geometry={nodes.Cube113_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube113_2"
            geometry={nodes.Cube113_2.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube046"
          position={[-2.94, 1.19, 2.06]}
          scale={[0.66, 0.08, 0.08]}
        >
          <mesh
            name="Cube114_1"
            geometry={nodes.Cube114_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube114_2"
            geometry={nodes.Cube114_2.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube047"
          position={[-2.94, 1.19, 1.79]}
          scale={[0.66, 0.08, 0.08]}
        >
          <mesh
            name="Cube115_1"
            geometry={nodes.Cube115_1.geometry}
            material={materials["Material.048"]}
          />
          <mesh
            name="Cube115_2"
            geometry={nodes.Cube115_2.geometry}
            material={materials["Material.047"]}
          />
        </group>
        <group
          name="Cube048"
          position={[-2.6, 1.55, 0.31]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.14, -0.45, -0.41]}
        >
          <mesh
            name="Cube116"
            geometry={nodes.Cube116.geometry}
            material={materials["Material.049"]}
          />
          <mesh
            name="Cube116_1"
            geometry={nodes.Cube116_1.geometry}
            material={materials["Material.051"]}
          />
        </group>
        <group
          name="Cube049"
          position={[-3.15, 1.55, 0.04]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[-0.14, -0.45, -0.41]}
        >
          <mesh
            name="Cube117"
            geometry={nodes.Cube117.geometry}
            material={materials["Material.050"]}
          />
          <mesh
            name="Cube117_1"
            geometry={nodes.Cube117_1.geometry}
            material={materials["Material.052"]}
          />
        </group>
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials["Material.057"]}
          position={[1.12, 1.1, 0.16]}
          rotation={[0, 0, -Math.PI]}
          scale={[-0.1, -0.1, -1.94]}
        />
        <mesh
          name="Cube097"
          geometry={nodes.Cube097.geometry}
          material={materials["Material.056"]}
          position={[-0.54, 1.1, 2.01]}
          rotation={[Math.PI, Math.PI / 2, 0]}
          scale={[-0.1, -0.1, -1.56]}
        />
        <mesh
          name="Cube098"
          geometry={nodes.Cube098.geometry}
          material={materials["Material.055"]}
          position={[-2.19, 1.19, 1.72]}
          rotation={[0.24, 0, -Math.PI]}
          scale={[-0.1, -0.09, -0.37]}
        />
        <mesh
          name="Cube099"
          geometry={nodes.Cube099.geometry}
          material={materials["Material.054"]}
          position={[-2.47, 1.27, 1.28]}
          rotation={[Math.PI, Math.PI / 2, 0]}
          scale={[-0.1, -0.09, -0.37]}
        />
        <mesh
          name="Garage"
          geometry={nodes.Garage.geometry}
          material={materials["Material.053"]}
          position={[-3.77, 1.17, 1.27]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.18, 0.26, 0.18]}
        />
        <mesh
          name="ConstructionTrucks"
          geometry={nodes.ConstructionTrucks.geometry}
          material={materials["Material.018"]}
          position={[1.61, 1.37, 2.13]}
          scale={[0.02, 0.03, 0.02]}
        >
          <mesh
            name="Cube025"
            geometry={nodes.Cube025.geometry}
            material={materials["Material.027"]}
            position={[1.65, -0.85, 1.36]}
            scale={0.39}
          />
          <mesh
            name="Cube026"
            geometry={nodes.Cube026.geometry}
            material={materials["Material.020"]}
            position={[2.65, -0.85, 1.36]}
            scale={0.39}
          />
          <mesh
            name="Cube027"
            geometry={nodes.Cube027.geometry}
            material={materials["Material.025"]}
            position={[7.62, -0.85, 1.36]}
            scale={0.39}
          />
          <mesh
            name="Cube028"
            geometry={nodes.Cube028.geometry}
            material={materials["Material.026"]}
            position={[6.47, -0.85, 1.36]}
            scale={0.39}
          />
          <mesh
            name="Cube031"
            geometry={nodes.Cube031.geometry}
            material={materials["Material.024"]}
            position={[1.65, -0.85, -1.17]}
            scale={0.39}
          />
          <mesh
            name="Cube032"
            geometry={nodes.Cube032.geometry}
            material={materials["Material.023"]}
            position={[2.65, -0.85, -1.17]}
            scale={0.39}
          />
          <mesh
            name="Cube050_3"
            geometry={nodes.Cube050_3.geometry}
            material={materials["Material.021"]}
            position={[7.62, -0.85, -1.17]}
            scale={0.39}
          />
          <mesh
            name="Cube051"
            geometry={nodes.Cube051.geometry}
            material={materials["Material.022"]}
            position={[6.47, -0.85, -1.17]}
            scale={0.39}
          />
          <group
            name="TruckTwo002"
            position={[4.65, 0.31, 0.05]}
            scale={[3.91, 1.26, 1.26]}
          >
            <mesh
              name="Cube002_1"
              geometry={nodes.Cube002_1.geometry}
              material={materials["Material.017"]}
            />
            <mesh
              name="Cube002_2"
              geometry={nodes.Cube002_2.geometry}
              material={materials["Material.004"]}
            />
          </group>
        </mesh>
        <mesh
          name="Fuel_Tanks"
          geometry={nodes.Fuel_Tanks.geometry}
          material={materials["Material.063"]}
          position={[1.94, 1.29, -0.76]}
          scale={0.23}
        >
          <mesh
            name="Cylinder002"
            geometry={nodes.Cylinder002.geometry}
            material={materials["Material.063"]}
            position={[5.29, 0, -2.82]}
          />
          <mesh
            name="Cylinder003"
            geometry={nodes.Cylinder003.geometry}
            material={materials["Material.063"]}
            position={[0, 0, -2.82]}
          />
          <mesh
            name="Cylinder004"
            geometry={nodes.Cylinder004.geometry}
            material={materials["Material.063"]}
            position={[5.29, 0, 0]}
          />
          <mesh
            name="Cylinder005"
            geometry={nodes.Cylinder005.geometry}
            material={materials["Material.063"]}
            position={[2.66, 0.35, -1.37]}
          />
        </mesh>
        <mesh
          name="Person024"
          geometry={nodes.Person024.geometry}
          material={materials["Material.044"]}
          position={[1.5, 1.56, -2.45]}
          rotation={[0, -1.39, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere025"
          geometry={nodes.Sphere025.geometry}
          material={materials["Material.045"]}
          position={[1.5, 1.6, -2.45]}
          rotation={[0, -0.57, 0]}
          scale={0.02}
        />
        <mesh
          name="Person025"
          geometry={nodes.Person025.geometry}
          material={materials["Material.044"]}
          position={[1.5, 1.56, -2.52]}
          rotation={[0, -1.39, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere026"
          geometry={nodes.Sphere026.geometry}
          material={materials["Material.045"]}
          position={[1.5, 1.6, -2.52]}
          rotation={[0, -0.57, 0]}
          scale={0.02}
        />
        <group
          name="ControlCenter"
          position={[-1.15, 1.18, -0.96]}
          scale={0.18}
        >
          <mesh
            name="Cube192"
            geometry={nodes.Cube192.geometry}
            material={materials["Material.070"]}
          />
          <mesh
            name="Cube192_1"
            geometry={nodes.Cube192_1.geometry}
            material={materials.Red}
          />
          <mesh
            name="Cube192_2"
            geometry={nodes.Cube192_2.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          name="Circle"
          geometry={nodes.Circle.geometry}
          material={materials["Material.018"]}
          position={[0.01, 1.37, -1.61]}
          rotation={[1.06, 0, -Math.PI / 2]}
          scale={0.19}
        />
        <mesh
          name="Person026"
          geometry={nodes.Person026.geometry}
          material={materials["Material.044"]}
          position={[1.24, 1.56, -2.82]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere027"
          geometry={nodes.Sphere027.geometry}
          material={materials["Material.045"]}
          position={[1.24, 1.6, -2.82]}
          scale={0.02}
        />
        <mesh
          name="Person027"
          geometry={nodes.Person027.geometry}
          material={materials["Material.044"]}
          position={[1.21, 1.56, -2.78]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere028"
          geometry={nodes.Sphere028.geometry}
          material={materials["Material.045"]}
          position={[1.21, 1.6, -2.78]}
          scale={0.02}
        />
        <mesh
          name="Cube070"
          geometry={nodes.Cube070.geometry}
          material={materials["Material.002"]}
          position={[-1.6, 1.13, 0]}
          scale={0.21}
        />
        <group
          name="Cube071"
          position={[0.47, 1.37, 1.37]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.13, -0.46, -0.12]}
        >
          <mesh
            name="Cube197"
            geometry={nodes.Cube197.geometry}
            material={materials["Material.010"]}
          />
          <mesh
            name="Cube197_1"
            geometry={nodes.Cube197_1.geometry}
            material={materials["Material.002"]}
          />
        </group>
        <mesh
          name="Person028"
          geometry={nodes.Person028.geometry}
          material={materials["Material.044"]}
          position={[-0.17, 1.03, 0.03]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere029"
          geometry={nodes.Sphere029.geometry}
          material={materials["Material.045"]}
          position={[-0.17, 1.07, 0.03]}
          scale={0.02}
        />
        <mesh
          name="Person029"
          geometry={nodes.Person029.geometry}
          material={materials["Material.044"]}
          position={[-0.21, 1.03, -0.02]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere030"
          geometry={nodes.Sphere030.geometry}
          material={materials["Material.045"]}
          position={[-0.21, 1.07, -0.02]}
          scale={0.02}
        />
        <group
          name="Cube074"
          position={[-0.62, 1.2, 1.6]}
          scale={[0.51, 0.19, 0.09]}
        >
          <mesh
            name="Cube203"
            geometry={nodes.Cube203.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            name="Cube203_1"
            geometry={nodes.Cube203_1.geometry}
            material={materials["Material.065"]}
          />
        </group>
        <group name="Cube075" position={[0, 1.11, 0]} scale={0.11}>
          <mesh
            name="Cube204"
            geometry={nodes.Cube204.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube204_1"
            geometry={nodes.Cube204_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group name="Cube076" position={[-0.66, 1.09, 0.66]} scale={0.11}>
          <mesh
            name="Cube205"
            geometry={nodes.Cube205.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube205_1"
            geometry={nodes.Cube205_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <group name="Cube077" position={[-0.91, 1.09, -0.37]} scale={0.11}>
          <mesh
            name="Cube206"
            geometry={nodes.Cube206.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            name="Cube206_1"
            geometry={nodes.Cube206_1.geometry}
            material={materials["Material.006"]}
          />
        </group>
        <mesh
          name="Person030"
          geometry={nodes.Person030.geometry}
          material={materials["Material.044"]}
          position={[-1.02, 1.07, 0.44]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere031"
          geometry={nodes.Sphere031.geometry}
          material={materials["Material.045"]}
          position={[-1.02, 1.11, 0.44]}
          scale={0.02}
        />
        <mesh
          name="Person031"
          geometry={nodes.Person031.geometry}
          material={materials["Material.044"]}
          position={[-0.91, 1.07, 0.5]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere032"
          geometry={nodes.Sphere032.geometry}
          material={materials["Material.045"]}
          position={[-0.91, 1.11, 0.5]}
          scale={0.02}
        />
        <mesh
          name="Person032"
          geometry={nodes.Person032.geometry}
          material={materials["Material.044"]}
          position={[-0.94, 1.07, 0.57]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere033"
          geometry={nodes.Sphere033.geometry}
          material={materials["Material.045"]}
          position={[-0.94, 1.11, 0.57]}
          scale={0.02}
        />
        <mesh
          name="Person033"
          geometry={nodes.Person033.geometry}
          material={materials["Material.044"]}
          position={[-1.02, 1.07, 0.6]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere034"
          geometry={nodes.Sphere034.geometry}
          material={materials["Material.045"]}
          position={[-1.02, 1.11, 0.6]}
          scale={0.02}
        />
        <mesh
          name="Person034"
          geometry={nodes.Person034.geometry}
          material={materials["Material.044"]}
          position={[-1.09, 1.07, 0.53]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere035"
          geometry={nodes.Sphere035.geometry}
          material={materials["Material.045"]}
          position={[-1.09, 1.11, 0.53]}
          scale={0.02}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={materials["Material.004"]}
          position={[1.39, 1.26, 1.82]}
          rotation={[-Math.PI, 0, 2.77]}
          scale={[-0.22, -0.03, -0.09]}
        />
        <mesh
          name="Person035"
          geometry={nodes.Person035.geometry}
          material={materials["Material.044"]}
          position={[-2.58, 1.21, 3.47]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere036"
          geometry={nodes.Sphere036.geometry}
          material={materials["Material.045"]}
          position={[-2.58, 1.23, 3.47]}
          scale={0.01}
        />
        <mesh
          name="Person036"
          geometry={nodes.Person036.geometry}
          material={materials["Material.044"]}
          position={[-2.61, 1.21, 3.43]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere037"
          geometry={nodes.Sphere037.geometry}
          material={materials["Material.045"]}
          position={[-2.61, 1.23, 3.43]}
          scale={0.01}
        />
        <mesh
          name="Person014"
          geometry={nodes.Person014.geometry}
          material={materials["Material.044"]}
          position={[-3.67, 1.13, 3]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere015"
          geometry={nodes.Sphere015.geometry}
          material={materials["Material.045"]}
          position={[-3.67, 1.15, 3]}
          scale={0.01}
        />
        <mesh
          name="Person015"
          geometry={nodes.Person015.geometry}
          material={materials["Material.044"]}
          position={[-3.69, 1.13, 2.96]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere016"
          geometry={nodes.Sphere016.geometry}
          material={materials["Material.045"]}
          position={[-3.69, 1.15, 2.96]}
          scale={0.01}
        />
        <mesh
          name="Person020"
          geometry={nodes.Person020.geometry}
          material={materials["Material.044"]}
          position={[-3.76, 1.12, 2.08]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere021"
          geometry={nodes.Sphere021.geometry}
          material={materials["Material.045"]}
          position={[-3.76, 1.14, 2.08]}
          scale={0.01}
        />
        <mesh
          name="Person021"
          geometry={nodes.Person021.geometry}
          material={materials["Material.044"]}
          position={[-3.79, 1.12, 2.04]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere022"
          geometry={nodes.Sphere022.geometry}
          material={materials["Material.045"]}
          position={[-3.79, 1.14, 2.04]}
          scale={0.01}
        />
        <mesh
          name="Person016"
          geometry={nodes.Person016.geometry}
          material={materials["Material.044"]}
          position={[-3.72, 1.11, 2.06]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere017"
          geometry={nodes.Sphere017.geometry}
          material={materials["Material.045"]}
          position={[-3.72, 1.14, 2.06]}
          scale={0.01}
        />
        <mesh
          name="Person017"
          geometry={nodes.Person017.geometry}
          material={materials["Material.044"]}
          position={[-3.75, 1.11, 2.02]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.02, 0.01, 0.01]}
        />
        <mesh
          name="Sphere018"
          geometry={nodes.Sphere018.geometry}
          material={materials["Material.045"]}
          position={[-3.75, 1.14, 2.02]}
          scale={0.01}
        />
        <mesh
          name="Person018"
          geometry={nodes.Person018.geometry}
          material={materials["Material.044"]}
          position={[0.29, 2.07, 1.58]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere019"
          geometry={nodes.Sphere019.geometry}
          material={materials["Material.045"]}
          position={[0.29, 2.11, 1.58]}
          scale={0.02}
        />
        <mesh
          name="Person019"
          geometry={nodes.Person019.geometry}
          material={materials["Material.044"]}
          position={[0.25, 2.07, 1.52]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere020"
          geometry={nodes.Sphere020.geometry}
          material={materials["Material.045"]}
          position={[0.25, 2.11, 1.52]}
          scale={0.02}
        />
        <mesh
          name="Person037"
          geometry={nodes.Person037.geometry}
          material={materials["Material.044"]}
          position={[-2.89, 1.31, 0.41]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere038"
          geometry={nodes.Sphere038.geometry}
          material={materials["Material.045"]}
          position={[-2.89, 1.35, 0.41]}
          scale={0.02}
        />
        <mesh
          name="Person038"
          geometry={nodes.Person038.geometry}
          material={materials["Material.044"]}
          position={[-2.93, 1.31, 0.35]}
          rotation={[0, -0.82, -Math.PI / 2]}
          scale={[0.03, 0.01, 0.01]}
        />
        <mesh
          name="Sphere039"
          geometry={nodes.Sphere039.geometry}
          material={materials["Material.045"]}
          position={[-2.93, 1.35, 0.35]}
          scale={0.02}
        />
        <group
          name="TruckOne"
          position={[3.04, 1.15, 3.3]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube064_1"
            geometry={nodes.Cube064_1.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube064_2"
            geometry={nodes.Cube064_2.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube008"
            geometry={nodes.Cube008.geometry}
            material={materials["Material.018"]}
            position={[-1.19, -0.25, -0.04]}
            scale={[0.26, 0.79, 0.79]}
          />
          {/* <mesh
            name="Cube011"
            geometry={nodes.Cube011.geometry}
            material={materials["Material.027"]}
            position={[-0.77, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          /> */}
          <mesh
            name="Cube012"
            geometry={nodes.Cube012.geometry}
            material={materials["Material.020"]}
            position={[-0.51, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube013_1"
            geometry={nodes.Cube013_1.geometry}
            material={materials["Material.025"]}
            position={[0.76, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials["Material.026"]}
            position={[0.47, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube015"
            geometry={nodes.Cube015.geometry}
            material={materials["Material.024"]}
            position={[-0.77, -0.92, -0.96]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube018"
            geometry={nodes.Cube018.geometry}
            material={materials["Material.022"]}
            position={[0.47, -0.92, -0.96]}
            scale={[0.1, 0.31, 0.31]}
          />
        </group>
        <mesh
          name="BirdNestImages"
          geometry={nodes.BirdNestImages.geometry}
          material={materials["Material.031"]}
          position={[-2.44, 1.47, -1.44]}
          rotation={[0, 0.3, 0]}
          scale={0.7}
        >
          <mesh
            name="BirdNestImages001"
            geometry={nodes.BirdNestImages001.geometry}
            material={materials.BirdNestProfile}
            position={[0.45, 1.39, -0.27]}
            rotation={[Math.PI / 2, 0, -3.14]}
            scale={[0.19, 2.11, 4.06]}
          />
          <mesh
            name="ImagePWLanding005"
            geometry={nodes.ImagePWLanding005.geometry}
            material={materials.BirdNestHome}
            position={[-0.02, 1.37, 0.5]}
            rotation={[Math.PI / 2, 0, -1.04]}
            scale={[0.19, 2.09, 4.02]}
          />
          <mesh
            name="ImagePWLanding007"
            geometry={nodes.ImagePWLanding007.geometry}
            material={materials.BirdNestMessageFeed}
            position={[-0.44, 1.39, -0.25]}
            rotation={[Math.PI / 2, 0, 1.03]}
            scale={[0.19, 2.11, 4.05]}
          />
        </mesh>
        <group
          name="TruckThree"
          position={[1.73, 1.38, 2]}
          rotation={[0, -0.29, 0]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube084_1"
            geometry={nodes.Cube084_1.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube084_2"
            geometry={nodes.Cube084_2.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Cube061"
          geometry={nodes.Cube061.geometry}
          material={materials["Material.018"]}
          position={[1.62, 1.37, 1.97]}
          rotation={[0, -0.29, 0]}
          scale={[0.02, 0.03, 0.02]}
        />
        <mesh
          name="Cube062"
          geometry={nodes.Cube062.geometry}
          material={materials["Material.027"]}
          position={[1.64, 1.35, 2.01]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube063"
          geometry={nodes.Cube063.geometry}
          material={materials["Material.020"]}
          position={[1.67, 1.35, 2.02]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube064"
          geometry={nodes.Cube064.geometry}
          material={materials["Material.025"]}
          position={[1.79, 1.35, 2.06]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube065"
          geometry={nodes.Cube065.geometry}
          material={materials["Material.026"]}
          position={[1.76, 1.35, 2.05]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube066"
          geometry={nodes.Cube066.geometry}
          material={materials["Material.024"]}
          position={[1.66, 1.35, 1.95]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube067"
          geometry={nodes.Cube067.geometry}
          material={materials["Material.023"]}
          position={[1.69, 1.35, 1.96]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube068"
          geometry={nodes.Cube068.geometry}
          material={materials["Material.021"]}
          position={[1.8, 1.35, 2]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube069"
          geometry={nodes.Cube069.geometry}
          material={materials["Material.022"]}
          position={[1.78, 1.35, 1.99]}
          rotation={[0, -0.29, 0]}
          scale={0.01}
        />
        <group
          name="TruckTwo003"
          position={[1.08, 1.23, -1.85]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube147"
            geometry={nodes.Cube147.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube147_1"
            geometry={nodes.Cube147_1.geometry}
            material={materials["Material.004"]}
          />
          <mesh
            name="Cube002"
            geometry={nodes.Cube002.geometry}
            material={materials["Material.018"]}
            position={[-1.19, -0.25, -0.04]}
            scale={[0.26, 0.79, 0.79]}
          />
          <mesh
            name="Cube079"
            geometry={nodes.Cube079.geometry}
            material={materials["Material.027"]}
            position={[-0.77, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube080"
            geometry={nodes.Cube080.geometry}
            material={materials["Material.020"]}
            position={[-0.51, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube081"
            geometry={nodes.Cube081.geometry}
            material={materials["Material.025"]}
            position={[0.76, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube082"
            geometry={nodes.Cube082.geometry}
            material={materials["Material.026"]}
            position={[0.47, -0.92, 1.04]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube083"
            geometry={nodes.Cube083.geometry}
            material={materials["Material.024"]}
            position={[-0.77, -0.92, -0.96]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube084"
            geometry={nodes.Cube084.geometry}
            material={materials["Material.023"]}
            position={[-0.51, -0.92, -0.96]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube085"
            geometry={nodes.Cube085.geometry}
            material={materials["Material.021"]}
            position={[0.76, -0.92, -0.96]}
            scale={[0.1, 0.31, 0.31]}
          />
          <mesh
            name="Cube086"
            geometry={nodes.Cube086.geometry}
            material={materials["Material.022"]}
            position={[0.47, -0.92, -0.96]}
            scale={[0.1, 0.31, 0.31]}
          />
        </group>
        <group
          name="TruckTwo004"
          position={[-2.43, 1.24, 3.35]}
          rotation={[0, 0, 0.1]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube157"
            geometry={nodes.Cube157.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube157_1"
            geometry={nodes.Cube157_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Cube052"
          geometry={nodes.Cube052.geometry}
          material={materials["Material.018"]}
          position={[-2.54, 1.22, 3.35]}
          rotation={[0, 0, 0.1]}
          scale={[0.02, 0.03, 0.02]}
        />
        <mesh
          name="Cube053"
          geometry={nodes.Cube053.geometry}
          material={materials["Material.027"]}
          position={[-2.5, 1.2, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube054"
          geometry={nodes.Cube054.geometry}
          material={materials["Material.020"]}
          position={[-2.48, 1.21, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube055"
          geometry={nodes.Cube055.geometry}
          material={materials["Material.025"]}
          position={[-2.36, 1.22, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube056"
          geometry={nodes.Cube056.geometry}
          material={materials["Material.026"]}
          position={[-2.38, 1.21, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube057"
          geometry={nodes.Cube057.geometry}
          material={materials["Material.024"]}
          position={[-2.5, 1.2, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube058"
          geometry={nodes.Cube058.geometry}
          material={materials["Material.023"]}
          position={[-2.48, 1.21, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube059"
          geometry={nodes.Cube059.geometry}
          material={materials["Material.021"]}
          position={[-2.36, 1.22, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube060"
          geometry={nodes.Cube060.geometry}
          material={materials["Material.022"]}
          position={[-2.38, 1.21, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <group
          name="TruckTwo005"
          position={[-2.73, 1.21, 3.35]}
          rotation={[0, 0, 0.1]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube167"
            geometry={nodes.Cube167.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube167_1"
            geometry={nodes.Cube167_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Cube087"
          geometry={nodes.Cube087.geometry}
          material={materials["Material.018"]}
          position={[-2.84, 1.19, 3.35]}
          rotation={[0, 0, 0.1]}
          scale={[0.02, 0.03, 0.02]}
        />
        <mesh
          name="Cube088"
          geometry={nodes.Cube088.geometry}
          material={materials["Material.027"]}
          position={[-2.8, 1.17, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube089"
          geometry={nodes.Cube089.geometry}
          material={materials["Material.020"]}
          position={[-2.78, 1.18, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube090"
          geometry={nodes.Cube090.geometry}
          material={materials["Material.025"]}
          position={[-2.66, 1.19, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube091"
          geometry={nodes.Cube091.geometry}
          material={materials["Material.026"]}
          position={[-2.68, 1.19, 3.38]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube092"
          geometry={nodes.Cube092.geometry}
          material={materials["Material.024"]}
          position={[-2.8, 1.17, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube093"
          geometry={nodes.Cube093.geometry}
          material={materials["Material.023"]}
          position={[-2.78, 1.18, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube094"
          geometry={nodes.Cube094.geometry}
          material={materials["Material.021"]}
          position={[-2.66, 1.19, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube095"
          geometry={nodes.Cube095.geometry}
          material={materials["Material.022"]}
          position={[-2.68, 1.19, 3.32]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <group
          name="TruckTwo001"
          position={[-0.02, 1.07, 0.3]}
          rotation={[0, 0, 0.1]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube207"
            geometry={nodes.Cube207.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube207_1"
            geometry={nodes.Cube207_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Cube078"
          geometry={nodes.Cube078.geometry}
          material={materials["Material.018"]}
          position={[-0.13, 1.05, 0.29]}
          rotation={[0, 0, 0.1]}
          scale={[0.02, 0.03, 0.02]}
        />
        <mesh
          name="Cube096"
          geometry={nodes.Cube096.geometry}
          material={materials["Material.027"]}
          position={[-0.09, 1.03, 0.33]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube100"
          geometry={nodes.Cube100.geometry}
          material={materials["Material.020"]}
          position={[-0.06, 1.03, 0.33]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube101"
          geometry={nodes.Cube101.geometry}
          material={materials["Material.025"]}
          position={[0.06, 1.04, 0.33]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube102"
          geometry={nodes.Cube102.geometry}
          material={materials["Material.026"]}
          position={[0.03, 1.04, 0.33]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube103"
          geometry={nodes.Cube103.geometry}
          material={materials["Material.024"]}
          position={[-0.09, 1.03, 0.27]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube104"
          geometry={nodes.Cube104.geometry}
          material={materials["Material.023"]}
          position={[-0.06, 1.03, 0.27]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube105"
          geometry={nodes.Cube105.geometry}
          material={materials["Material.021"]}
          position={[0.06, 1.04, 0.27]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <mesh
          name="Cube106"
          geometry={nodes.Cube106.geometry}
          material={materials["Material.022"]}
          position={[0.03, 1.04, 0.27]}
          rotation={[0, 0, 0.1]}
          scale={0.01}
        />
        <group
          name="TruckTwo006"
          position={[-1.48, 1.18, 1.38]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={[0.1, 0.03, 0.03]}
        >
          <mesh
            name="Cube217"
            geometry={nodes.Cube217.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            name="Cube217_1"
            geometry={nodes.Cube217_1.geometry}
            material={materials["Material.004"]}
          />
        </group>
        <mesh
          name="Cube107"
          geometry={nodes.Cube107.geometry}
          material={materials["Material.018"]}
          position={[-1.38, 1.13, 1.38]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={[0.02, 0.03, 0.02]}
        />
        <mesh
          name="Cube108"
          geometry={nodes.Cube108.geometry}
          material={materials["Material.027"]}
          position={[-1.42, 1.13, 1.35]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube109"
          geometry={nodes.Cube109.geometry}
          material={materials["Material.020"]}
          position={[-1.45, 1.14, 1.35]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube110"
          geometry={nodes.Cube110.geometry}
          material={materials["Material.025"]}
          position={[-1.56, 1.18, 1.36]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube111"
          geometry={nodes.Cube111.geometry}
          material={materials["Material.026"]}
          position={[-1.54, 1.17, 1.36]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube112"
          geometry={nodes.Cube112.geometry}
          material={materials["Material.024"]}
          position={[-1.42, 1.13, 1.41]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube113"
          geometry={nodes.Cube113.geometry}
          material={materials["Material.023"]}
          position={[-1.44, 1.14, 1.41]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube114"
          geometry={nodes.Cube114.geometry}
          material={materials["Material.021"]}
          position={[-1.56, 1.18, 1.42]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Cube115"
          geometry={nodes.Cube115.geometry}
          material={materials["Material.022"]}
          position={[-1.53, 1.17, 1.42]}
          rotation={[-3.12, -0.08, -2.79]}
          scale={0.01}
        />
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={materials["default"]}
          position={[-1.15, 0.48, 4.79]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.76}
        />
        <mesh
          name="Text001"
          geometry={nodes.Text001.geometry}
          material={materials["default"]}
          position={[2.8, 0.61, -4.96]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.6}
        />
        <mesh
          name="Text002"
          geometry={nodes.Text002.geometry}
          material={materials["default"]}
          position={[-4.48, 0.55, -1.21]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.67}
        />
        <mesh
          name="Text003"
          geometry={nodes.Text003.geometry}
          material={materials["default"]}
          position={[4.68, 0.55, 3.16]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.54}
        />
        <mesh
          name="Text004"
          geometry={nodes.Text004.geometry}
          material={materials["default"]}
          position={[-3.24, 0.03, 4.79]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.54}
        />
        <mesh
          name="Text005"
          geometry={nodes.Text005.geometry}
          material={materials["default"]}
          position={[-4.48, 0.03, -2.71]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
          scale={0.54}
        />
        <mesh
          name="Text006"
          geometry={nodes.Text006.geometry}
          material={materials["default"]}
          position={[1.44, 0.03, -4.96]}
          rotation={[Math.PI / 2, 0, Math.PI]}
          scale={0.54}
        />
        <mesh
          name="Text007"
          geometry={nodes.Text007.geometry}
          material={materials["default"]}
          position={[4.68, 0.02, 3.83]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.54}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.028"]}
          position={[-2.41, 1.28, -1.48]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[-0.89, -0.2, -0.89]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/LandingAnimationCompressed.glb");
